# highlighter: pygments
highlighter: rouge

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://wakojia-pei.github.io/
devurl: http://localhost:4000/
name: WakoJia-Pei
title: WakoJia-Pei | Another yet unique freak is showing a freakshow
description: "WakoJia-Pei's personal weblog, on coding or such stuff"

my:
    displayName: WakoJia
    realName: WakoJia-Pei
    realName_cn: ***
    jobTitle: "PHP Coder"
    contact:
        qq: 724606412
        email: pwjiang@163.com
        github: https://github.com/WakoJia-Pei
        qzone: http://724606412.qzone.qq.com
        tel: 13772909507
        address:
            country: China
            state: 
            city: Xi'an
            distribute: YanTa
            postcode: 000000
            cell: "AnHuiLi"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap | Vue"]
        backend: ["Java", "MySQL", "Python"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Eclipse | WebStorm | Pycharm"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
